### Cadastro de usuário
POST http://localhost:3003/user
Content-Type: application/json

{
    "name":"Cassiano",
    "email":"cassiano@gmail.com",
    "password":"123456",
    "typeUser":"CNPJ"

}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"mina@gmail.com",
    "password":"123456"
}

### Search companies
GET http://localhost:3003/category/categoria-B
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMDIwMTNjLTIyZGUtNDA3MC1hYzg3LTMzNTU3MTgxZjU0NSIsImlhdCI6MTY1MTI1Njk2NiwiZXhwIjoxNjUxMzQzMzY2fQ.upn_piW0Q9pY_eqfs7dUFCIMRPTDzBifc1t03UWZtiQ